# Generated by Django 2.2.4 on 2020-12-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='name',
            new_name='network',
        ),
        migrations.RemoveField(
            model_name='show',
            name='networks',
        ),
        migrations.AddField(
            model_name='show',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='title',
            field=models.CharField(default='newtitle', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Network',
        ),
    ]
