# Generated by Django 2.2.4 on 2020-12-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow_app', '0002_auto_20201215_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(null=True, verbose_name='%m-%d-%y'),
        ),
    ]
