# Generated by Django 2.2.4 on 2020-12-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow_app', '0003_auto_20201215_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
