# Generated by Django 2.2.4 on 2020-12-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow_app', '0004_auto_20201215_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default='Nothing for now', max_length=255),
            preserve_default=False,
        ),
    ]
